name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:18-alpine
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g pnpm
      - run: npm it --frozen-lockfile
